version: '3'

services:
  main-service:
    build: ./main_service
    image: chatbot-main-service
    ports:
      - "5000:5000"
    depends_on:
      - api-service

  api-service:
    build: ./api_service
    image: chatbot-api-service
    ports:
      - "5001:5001"
