name: Chatbot Microservices CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (to support building multi-platform images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Install docker-compose
      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Step 4: Build Docker images for each service (main-service and api-service)
      - name: Build Docker images
        run: |
          docker-compose build --no-cache

      # Step 5: Run API tests (using pytest)
      - name: Run tests for API service
        run: |
          docker-compose run api-service pytest tests/test_api.py

      # Step 6: Run Frontend tests (using Selenium)
      - name: Run tests for Frontend (Selenium)
        run: |
          docker-compose run main-service pytest tests/test_frontend.py

      # Step 7: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 8: Push Docker images to Docker Hub
      - name: Push Docker images to Docker Hub
        run: |
          docker-compose push

  push_code:
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs only after the build job is successful

    steps:
      # Step 1: Checkout the code from the repository again (for deployment purposes)
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Git user for committing code back to GitHub (optional)
      - name: Set up Git user
        run: |
          git config --global user.name "Yousef-Cyborg"
          git config --global user.email "yousef.ahmad@cyborg-automation.com"

      # Step 3: Commit and push code changes (with authentication via GitHub token)
      - name: Commit and push changes
        run: |
          git remote add origin https://github.com/Yousef-Cyborg/DOCKER.git
          git branch -M main
          git push -u origin main
